name: Get PR Label

on:
  push:
    branches:
      - main

jobs:
  get_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Merged PR Number
        id: pr_number
        run: |
          pr_number=$(git log --grep="Merge pull request #[0-9]\+" --pretty=oneline -1 | sed -En "s/.*#([[:digit:]]+).*/\1/p")
          echo "::set-output name=pr_number::$pr_number"


      - name: Get PR Label
        id: pr_label
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          NUMBER=${{ steps.pr_number.outputs.pr_number }}
          
          LABELS=$(curl -sH "Authorization: token $TOKEN" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/$NUMBER" | jq '.labels[].name')
          
          echo "::set-output name=label::${LABELS}"

      - name: Print PR Label
        run: echo "PR label is ${{ steps.pr_label.outputs.label }}"