name: PR Label Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled


jobs:
  pr_label_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PR labels
        run: |
          # 获取提取请求信息和标签列表
          pr_info=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      --header "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")
          labels=$(echo "${pr_info}" | jq -r '.labels[]?.name')
          
          # 检查标签中是否包含"field1"
          if echo "${labels}" | grep -q 'field1'; then 
            echo "Label field1 found! congratulation" 
            # 这里可以添加其他需要执行的步骤
          else 
            echo "Label field1 not found." 
            exit 1  # 终止 Workflow 并标记为失败
          fi
