name: PR Label Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - reopened


jobs:
  pr_label_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Label checker for pull requests
        uses: agilepathway/label-checker@v1.5.9
        with:
          one_of: major,minor,patch,bug
          repo_token: ${{ secrets.GITHUB_TOKEN }}