name: Pull Request

on:
  pull_request:
    issues:
      - created

jobs:
  issue_check:
    name: Check Issue
    if: github.event_name == 'pull_request' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue Title
        uses: actions/issues/check-title@v1
        with:
          title-pattern: '#[0-9]+'
      - name: Create Issue Action
        uses: actions/issues/create@v1
        with:
          api-endpoint: issues
          title: 'Check PR #{{ github.event.issue.number }}'
          body: |
            ## Please enter the type of change  
            ## Major (Breaking changes)  
            ## Patch (Bug fixes and minor enhancements)  
            ## Minor (New features and major enhancements)
          labels: |
            bug  
            enhancement  
            feature
  merge_check:
    name: Merge Check
    if: github.event_name == 'issue' && github.event.issue.number == {{ github.event.pull_request.number }} && github.event.issue.action == 'created' && github.event.issue.label_added contains 'check/passed'
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: actions/merge@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ inputs.base_sha }}
          merge-method: squash
          only-fetch-master-branch: true